#!/bin/bash

set -e

if [[ "$@" =~ "--container" ]]; then
    containerName="emerald"

    if [[ "$@" =~ "--build" ]]; then
        docker rm --force $containerName > /dev/null
    fi

    if [ ! "$(docker ps -q -f name=$containerName)" ]; then
        echo "Container <$containerName> does not exist, building"
    
        docker build . -t emerald && docker run -dt --name $containerName --network "host" emerald
    fi

    args=$@
    args=( "${args[@]/--container}" ) 
    args=( "${args[@]/--build}" ) 

    echo "Running command with args <$(echo $args | xargs)>"

    docker exec emerald sh -c "if [ -d /screenshots ]; then rm -r /screenshots; fi"
    docker exec emerald sh -c "dotnet build && bash run $args --dir /screenshots"

    echo "copying screenshots"

    docker cp emerald:screenshots/ .

    echo ""

    ls -lh screenshots/

    exit 0
fi

if [[ "$@" =~ "--build" ]]; then
    echo "building"
    dotnet build Emerald.sln
fi

dotnet run --no-build --project Emerald.Cli/Emerald.Cli.csproj $@